### ISSUE TITLE
feat: fix Search bar popup problem

### ISSUE THREAD

**Issue by itsharshitrwt** [suryanshsingh2001/MyLibrary#68]
**Issue**
Whenever we try to search for any books in the search bar, a pop-up appears [ Request failed ], which is irritating because it appears with every search, and this needs to be fixed.

![Screenshot 2024-10-08 121904](https://github.com/user-attachments/assets/94ed0fc8-eb33-4db0-a8b7-45e718a39573)

This can significantly degrade the user experience with the website.

Can i work on improving it, plz assign ??

**Comment by suryanshsingh2001** [comment]
Hi @itsharshitrwt, I am unable to replicate this issue on the production website. Can you some more information on the issue, please feel free to use this template while explaining issues



## Bug Report Template

### **Describe the bug**
_A clear and concise description of what the bug is. Example: "The application crashes when..."_

### **To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '...'
3. Scroll down to '...'
4. See error

### **Expected behavior**
_A clear and concise description of what you expected to happen._

### **Screenshots**
_If applicable, add screenshots to help explain your problem._

### **Environment (please complete the following information):**
- **OS**: [e.g., Windows, macOS]
- **Browser**: [e.g., Chrome, Safari]
- **Version**: [e.g., 22]
- **Other relevant environment details** (e.g., Node version, database version)

### **Additional context**
_Add any other context about the problem here (e.g., error logs, stack traces)._

---

### **Optional Sections (if relevant):**

- **Priority (Low / Medium / High)**  
- **Is this issue blocking your progress?**  
- **Can you submit a PR to fix this?**

**Comment by itsharshitrwt** [comment]
hi @suryanshsingh2001  i think this issue is from my end , and not in the production should i close this? i don't know if maybe other people are also facing this...

**Comment by suryanshsingh2001** [comment]
> hi @suryanshsingh2001 i think this issue is from my end , and not in the production should i close this? i don't know if maybe other people are also facing this...

Hey @itsharshitrwt , 
It seems like an issue with API keys probably or google cloud console as far I can see.
Feel free to look for other issues, or add one of your own again.
